### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by vanelyang** [USTCLH/OCC-VO#2]
感谢您开源代码，希望没有打扰到您，有一些疑问：

1、表1中的数据是对 150 个场景的结果取平均值得到的嘛；
2、表4中的结果如何得到，可以提供相关代码嘛；

期待您的回复，谢谢。

**Comment by USTCLH** [comment]
1、表1中的RMSE项，是对150个场景绝对位姿误差的均方根误差，并非其平均值；
2、表4中的数据是将每个场景的真值与预测结果，先进行配准，再计算文章提到的三个指标，最后各自对150个场景指标结果取均值得到的。

**Comment by vanelyang** [comment]
用 evo_ape 命令可以评估单个场景的RMSE，150 个场景的RMSE该怎么计算呢

**Comment by USTCLH** [comment]
抱歉，我的描述有误，确实是取150个场景的RMSE的均值。

**Comment by vanelyang** [comment]
好的，谢谢您的回复。
